"""add_field_description_in_books_table

Revision ID: f1532deaa8ee
Revises: 1fa1d3e17c08
Create Date: 2025-06-11 16:31:46.898714

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f1532deaa8ee"
down_revision: Union[str, None] = "1fa1d3e17c08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books",
        sa.Column(
            "description", sa.String(), server_default="...", nullable=True
        ),
    )
    op.alter_column(
        "borrowed_books",
        "borrow_date",
        existing_type=postgresql.TIMESTAMP(),
        server_default="now()",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "borrowed_books",
        "borrow_date",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text(
            "'2025-06-11 15:50:00.723852'::timestamp without time zone"
        ),
        existing_nullable=False,
    )
    op.drop_column("books", "description")
    # ### end Alembic commands ###
