"""added deleted_at field in books db

Revision ID: 23eb5b79c0ca
Revises: 0841ee106983
Create Date: 2025-11-06 20:27:31.894463

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "23eb5b79c0ca"
down_revision: Union[str, None] = "0841ee106983"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "borrowed_books",
        "borrow_date",
        existing_type=postgresql.TIMESTAMP(),
        server_default="now()",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "borrowed_books",
        "borrow_date",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text(
            "'2025-11-06 20:27:02.561642'::timestamp without time zone"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
