"""trying again added deleted_at on books table

Revision ID: 1112aa9fbd20
Revises: 23eb5b79c0ca
Create Date: 2025-11-06 23:02:34.027147

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1112aa9fbd20"
down_revision: Union[str, None] = "23eb5b79c0ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.alter_column(
        "borrowed_books",
        "borrow_date",
        existing_type=postgresql.TIMESTAMP(),
        server_default="now()",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "borrowed_books",
        "borrow_date",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text(
            "'2025-11-06 20:27:39.222219'::timestamp without time zone"
        ),
        existing_nullable=False,
    )
    op.drop_column("books", "deleted_at")
    # ### end Alembic commands ###
