"""fix_borrow_date_in_borrowed_books_table

Revision ID: 9dfa98e51f77
Revises: bf8fb9359c70
Create Date: 2025-06-10 11:35:33.839494

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9dfa98e51f77"
down_revision: Union[str, None] = "bf8fb9359c70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "borrowed_books",
        "borrow_date",
        existing_type=postgresql.TIMESTAMP(),
        server_default="now()",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "borrowed_books",
        "borrow_date",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text(
            "'2025-06-10 09:22:09.36747'::timestamp without time zone"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
