"""add_constraints_for_books_table

Revision ID: f46c96c7c35e
Revises: acfb9e384cc3
Create Date: 2025-06-09 09:55:25.896676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f46c96c7c35e"
down_revision: Union[str, None] = "acfb9e384cc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "borrowed_books",
        "borrow_date",
        existing_type=postgresql.TIMESTAMP(),
        server_default="now()",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "borrowed_books",
        "borrow_date",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text(
            "'2025-06-09 07:21:08.030756'::timestamp without time zone"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
