"""added deleted_at field in users db

Revision ID: 0841ee106983
Revises: f1532deaa8ee
Create Date: 2025-11-06 20:26:54.366481

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0841ee106983"
down_revision: Union[str, None] = "f1532deaa8ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "borrowed_books",
        "borrow_date",
        existing_type=postgresql.TIMESTAMP(),
        server_default="now()",
        existing_nullable=False,
    )
    op.add_column(
        "users", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted_at")
    op.alter_column(
        "borrowed_books",
        "borrow_date",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text(
            "'2025-06-11 16:32:03.20634'::timestamp without time zone"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
