"""added_relationship_between_tables

Revision ID: 4213aa0f4a3f
Revises: 07edc4fe5ce7
Create Date: 2025-06-08 23:41:20.202280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4213aa0f4a3f'
down_revision: Union[str, None] = '07edc4fe5ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrowed_books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('borrow_date', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['users.id'], name=op.f('fk_borrowed_books_book_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reader_id'], ['books.id'], name=op.f('fk_borrowed_books_reader_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_borrowed_books'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borrowed_books')
    # ### end Alembic commands ###
